### ISSUE TITLE
cephadm_status.py

### ISSUE THREAD

**Issue by sebastian-philipp** [linuxkidd/ceph-misc#1]
A while ago I created https://gist.github.com/sebastian-philipp/8e18f4815e90dc0f51fe3fbff8c8aae5 to fetch an expressive overview about the current state of the control plane. Might be interesting for you

**Comment by linuxkidd** [comment]
Hi @sebastian-philipp .. Sorry for missing this for... so, so long..  Thanks for the link!  The script definitely looks like it would be useful for a quick overview of the environment.
